### PR TITLE
Fix for "Message: 'chromedriver' executable needs to be in PATH. Please

### PR DESCRIPTION
**Pull request by tmciver**
See https://sites.google.com/a/chromium.org/chromedriver/home error on non-Windows OS's.

### CODE REVIEW

**Comment by inAudible-NG** [comment]
Thanks for this PR. However, this change has been proposed, and rejected before multiple times. See closed PR(s) for the rationale.

**Comment by tmciver** [comment]
The only rationale I see for this is [here](https://github.com/inAudible-NG/audible-activator/pull/34#issuecomment-309257063) where it's stated `"(imagine PATH problems on Windows)"`.  Has there actually been path problems on Windows?  If so, why not special case it for Windows users?  It seems to me you have a real usability issue for both Mac and Linux (and Windows?) users by forcing them to either link to, move or download chromedriver, evidenced by so many attempts to fix this problem.

**Comment by inAudible-NG** [comment]
The current set of code+instructions work everywhere (macOS, Linux, Windows) as they are written and without requiring any sort of elevated privileges (think of shared systems). They are meant to be robust and foolproof. Paying a slight cost of convenience cost (e.g. not relying on system package manager for installing ChromeDriver) is OK considering these main motives.

Thanks for understanding.

**Comment by inAudible-NG** [comment]
A good idea might be to auto-detect if ChromeDriver is already present in `PATH` (or at some fixed set of paths) and to automatically use it. This should satisfy everyone, right?

Such a pull request would be welcome.

**Comment by inAudible-NG** [comment]
It seem this was suggested in PR https://github.com/inAudible-NG/audible-activator/pull/39/files.

**Comment by corbolais** [comment]
Hey,

I cannot see your point in closing #39 or #37. As you stated in the previous comment a solution per your second last comment has been PR'ed.

I fail to find a merge of the referenced commits in #39.

Why don't you just merge it so everyone may profit from it. There seems no downside to it.

cheers

**Comment by inAudible-NG** [comment]
I will be merging support for chromedriver-autodetection-support-for-ubuntu soon. Thanks!

**Comment by ex-nerd** [comment]
Just an FYI that this error happens on MacOS if chromedriver is installed via homebrew (it goes into `/usr/local/bin/chromedriver`).  I worked around it by switching the path `else` clause to read `chromedriver` instead of `./chromedriver` -- so that it actually *is* detected from `$PATH` instead of the hard-coded values inside of `audible-activator.py`

**Comment by inAudible-NG** [comment]
I can add auto-detection of `/usr/local/bin/chromedriver` path.

**Comment by corbolais** [comment]
> It seem this was suggested in PR https://github.com/inAudible-NG/audible-activator/pull/39/files.

Why don't you just merge the PR and additionally add the `auto-detection of /usr/local/bin/chromedriver`?

I seem unable to grasp the underlying difficulty. Please explain.

Thank you.

cheers

**Pull request closed without merging**
