### PR TITLE
Use Chrome driver in path if not present elsewhere

### PR DESCRIPTION
**Pull request by l0b0**
Also add Chrome driver in a Nix shell so that it's installed in a single command.

### CODE REVIEW

**Comment by l0b0** [comment]
Ping?

**Review by dreirund — APPROVED** [review]
I already have come up with this on my own. I strongly suggest adapting this change, as it makes the software work with system wide installed `chromedriver`.

**Comment by l0b0** [comment]
This project seems to be dead, ~so I've [forked](https://gitlab.com/engmark/audible-activator) it. I'll try to make some time soon to make sure it's released to PyPI. Feel free to contribute over there.~ but since its description says "Using https://github.com/inAudible-NG/tables project instead is recommended." I'll just delete this.

**Comment by dreirund** [comment]
Ahoj

> This project seems to be dead, so I've forked [https://gitlab.com/engmark/audible-activator] it.

At yor fork I read

> Deletion pending. This project will be deleted on 2023-06-15. Repository and other project resources are read-only.

What is happening?

**Comment by l0b0** [comment]
> What is happening?

You'll need to refresh this page - I changed my mind.

**Comment by dreirund** [comment]
> but since its description says "Using 
> https://github.com/inAudible-NG/tables project instead is recommended." 
> I'll just delete this.

I have tried https://github.com/inAudible-NG/tables but could not get it 
to work. But I could not report any issue because issue tracker is 
deactivated.

I have emailed them a few months ago, though, but no reaction:

> I try to build and install your "Plugin for RainbowCrack to recover
> your own Audible activation data (activation_bytes) in an offline
> manner.".
> 
> However, I encounter some issues.
> 
> When I clone your source [1], I see that you ship some precompiled
> old binaries from the rainbowcrack project, which is definitely not 
> your
> code. It is then unclear for me how I cleanly install your plugin to a
> system's rainbowcrack.
> 
> Can you write an installation instruction?
> 
> (I am on GNU/Linux.)
> 
> Regards!
> 
> [1]
> https://github.com/inAudible-NG/tables

The issue is that they somehow ship some precompiled binaries from the 
rainbowcrack project itself and it completely unclear for me as packager 
or as user how to stitch things together to get it to work.

Do you know how to get it to work?

And the project also did not get updates since 2 years.

Regards!

**Comment by l0b0** [comment]
> Do you know how to get it to work?

No, sorry. But there does seem to be other projects providing the same service.

**Pull request closed without merging**
