### PR TITLE
Update audible-activator.py

### PR DESCRIPTION
**Pull request by wolfi101**
Had problems on OSX 10.10.5 with chromedriver and wanted to share how I solved it!
Documentation of how to install geckodriver.

### CODE REVIEW

**Comment by mymainmanbrown** [comment]
Without having actually tested it, I like it.  I like having the option to use firefox, and I like having a little bit of text telling me that the random letters and numbers are the activation bytes :)

**Comment by inAudible-NG** [comment]
Thanks! I have manually merged this PR with some minor changes. Also, I have added you to the credits section.

**Comment by wolfi101** [comment]
Hi, I just wanted to indicate that the documentation should be updated regarding the installation of geckodriver for those who would like to use firefox.

**Comment by inAudible-NG** [comment]
Thanks for the tip.

However, I never had to install `geckodriver` or any other software to use Selenium with Firefox. It just works as it is, at least on Fedora.

**Comment by wolfi101** [comment]
Interesting. I just tried it on OSX and got the error message:
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by inAudible-NG** [comment]
I will add something to `README.md` if multiple users run into the same problem. Thanks.

**Pull request closed without merging**
